import os

BASE_PATH = os.path.dirname(__file__)
DIMENSIIONS = COLUMNS, ROWS = 12, 22
TILE_SIZE = TILE_WIDTH, TILE_HEIGHT = 40, 40
SMALL_TILE_SIZE = SMALL_TILE_WIDTH, SMALL_TILE_HEIGHT = 20, 20
SIZE = WIDTH, HEIGHT = COLUMNS * TILE_WIDTH, ROWS * TILE_HEIGHT
FPS = 60

DEBUG = False
