import os

BASE_PATH = os.path.dirname(__file__)
DIMENSIIONS = COLUMNS, ROWS = 12, 22
TILE_SIZE = TILE_WIDTH, TILE_HEIGHT = 40, 40
SIZE = WIDTH, HEIGHT = COLUMNS * TILE_WIDTH, ROWS * TILE_HEIGHT
FPS = 60
